<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 5.0.1 (Python 3.10.8 on win32)" generated="20221023 19:59:18.883" rpa="false" schemaversion="3">
<suite id="s1" name="desafio API" source="c:\DesafioABC\DesafioAPI\desafio_API.robot">
<test id="s1-t1" name="CT002 - Criar uma chamada POST e validar o retorno" line="11">
<kw name="Dado que eu verifico se a api esta ONLINE">
<msg timestamp="20221023 19:59:19.521" level="FAIL">No keyword with name 'Dado que eu verifico se a api esta ONLINE' found.</msg>
<status status="FAIL" starttime="20221023 19:59:19.521" endtime="20221023 19:59:19.521"/>
</kw>
<kw name="E realizo um POST">
<status status="NOT RUN" starttime="20221023 19:59:19.529" endtime="20221023 19:59:19.529"/>
</kw>
<kw name="Entao confiro status code">
<arg>200</arg>
<status status="NOT RUN" starttime="20221023 19:59:19.537" endtime="20221023 19:59:19.545"/>
</kw>
<status status="FAIL" starttime="20221023 19:59:19.513" endtime="20221023 19:59:19.545">No keyword with name 'Dado que eu verifico se a api esta ONLINE' found.</status>
</test>
<status status="FAIL" starttime="20221023 19:59:18.891" endtime="20221023 19:59:19.545"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="desafio API">desafio API</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20221023 19:59:19.145" level="ERROR">Error in file 'c:\DesafioABC\DesafioAPI\desafio_API.robot' on line 4: Resource file 'ResourseAPI.robot' does not exist.</msg>
</errors>
</robot>
